#!/usr/bin/env python3
"""Builds the Sky concept pages from src/<page>.{html,css,js} and one shared frame.
Run from design-concepts/:  python3 build-sky.py"""
import os
PAGES = [  # file, title, nav, source
  ('e-weather.html','Weather','brief','weather'),
  ('e-timing.html','Timing','brief','timing'),
  ('e-terrain.html','Terrain & snow','brief','terrain'),
  ('e-route.html','Route','brief','route'),
  ('e-sources.html','Checks & sources','brief','sources'),
  ('e-gear.html','Gear & actions','brief','gear'),
  ('e-plan.html','Plan','plan','plan'),
]
CHAPTERS = [p for p in PAGES if p[2]=='brief']
NAV = [('brief','Brief','s-doc','e-sky.html'),('plan','Plan','s-plan','e-plan.html'),('cmp','Compare','s-cmp','#'),('saved','Saved','s-saved','#'),('watch','Watchlist','s-bell','#')]
rd = lambda p: open(p).read() if os.path.exists(p) else ''
sym = rd('src/symbols.svg')
def esc(t): return t.replace('&','&amp;')
for i,(fn,title,nav,src) in enumerate(PAGES):
    ON = ' class="on" aria-current="page"'
    link = lambda k,lbl,ic,h: '<a href="%s"%s><svg class="sym"><use href="#%s"/></svg>%s</a>' % (h, ON if k==nav else '', ic, lbl)
    side = ''.join(link(*n) for n in NAV)
    tabs = side
    if nav=='brief':
        tool = f'<a class="back" href="e-sky.html"><svg class="sym"><use href="#s-chev"/></svg>Brief</a><span class="ttl">{esc(title)}</span><span style="flex:1"></span><button class="tbtn" aria-label="Share"><svg class="sym"><use href="#s-share"/></svg><span class="lbl">Share</span></button>'
        ci = [c[0] for c in CHAPTERS].index(fn)
        prev = CHAPTERS[ci-1] if ci>0 else None; nxt = CHAPTERS[ci+1] if ci+1<len(CHAPTERS) else None
        pager = '<nav class="pager" aria-label="Chapters">' + (f'<a href="{prev[0]}"><span>Previous</span><b>‹ {esc(prev[1])}</b></a>' if prev else '<a href="e-sky.html"><span>Back to</span><b>‹ Brief</b></a>') + (f'<a class="next" href="{nxt[0]}"><span>Next</span><b>{esc(nxt[1])} ›</b></a>' if nxt else '<a class="next" href="e-sky.html"><span>Done</span><b>Brief ›</b></a>') + '</nav>'
    else:
        tool = f'<span class="ttl" style="position:static;transform:none">{esc(title)}</span><span style="flex:1"></span>'
        pager = ''
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<title>{esc(title)} · Sky</title>
<link rel="stylesheet" href="sky.css"><link rel="stylesheet" href="pages.css">
<style>
{rd(f"src/{src}.css")}
</style></head><body>
<!-- generated by build-sky.py from src/{src}.* : edit the sources, not this file -->
{sym}
<div class="app">
 <nav class="sidebar" aria-label="Main">
  <div class="brand"><svg class="sym"><use href="#s-mtn"/></svg>Backcountry Conditions</div>
  {side}
  <span class="sp"></span>
  <a><svg class="sym"><use href="#s-gear"/></svg>Settings</a>
 </nav>
 <div>
  <div class="toolbar detail">{tool}</div>
  <main class="page">
{rd(f"src/{src}.html")}
{pager}
  </main>
 </div>
</div>
<nav class="tabbar" aria-label="Main">{tabs}</nav>
<script src="shared.js"></script>
<script src="sky-lib.js"></script>
<script>
{rd(f"src/{src}.js")}
</script>
</body></html>
'''
    open(fn,'w').write(html)
    print('built', fn)
