#!/usr/bin/env bash
# Deploy a private PostgreSQL container on the SummitSafe VPS.
#
# Run as the deploy user from any directory:
#   /opt/summitsafe/scripts/deploy-postgres.sh
#
# The script is safe to rerun. On first run it appends strong credentials and
# DATABASE_URL to /opt/summitsafe/.env; it never replaces existing env values.

set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$APP_DIR/.env"
VOLUME_NAME="summitsafe_postgres-data"
DEFAULT_DB="summitsafe"
DEFAULT_USER="summitsafe_app"

cd "$APP_DIR"

fail() {
  echo "Error: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command '$1' is not installed."
}

read_env_value() {
  local key="$1"
  awk -v key="$key" '
    index($0, key "=") == 1 { value = substr($0, length(key) + 2) }
    END { sub(/\r$/, "", value); print value }
  ' "$ENV_FILE"
}

append_env_value() {
  local key="$1"
  local value="$2"
  printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
}

require_command docker
require_command openssl
require_command curl
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is not available."

if [ ! -f "$ENV_FILE" ]; then
  [ -f "$APP_DIR/backend/.env.example" ] || fail "backend/.env.example is missing."
  cp "$APP_DIR/backend/.env.example" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "==> Created $ENV_FILE from backend/.env.example"
fi
chmod 600 "$ENV_FILE"

postgres_db="$(read_env_value POSTGRES_DB)"
postgres_user="$(read_env_value POSTGRES_USER)"
postgres_password="$(read_env_value POSTGRES_PASSWORD)"
database_url="$(read_env_value DATABASE_URL)"

credential_count=0
[ -n "$postgres_db" ] && credential_count=$((credential_count + 1))
[ -n "$postgres_user" ] && credential_count=$((credential_count + 1))
[ -n "$postgres_password" ] && credential_count=$((credential_count + 1))

if [ "$credential_count" -ne 0 ] && [ "$credential_count" -ne 3 ]; then
  fail "POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD must either all be set or all be absent in $ENV_FILE."
fi

if [ "$credential_count" -eq 0 ]; then
  if [ -n "$database_url" ]; then
    fail "DATABASE_URL already exists in $ENV_FILE, but local PostgreSQL credentials are missing. The existing value was not changed."
  fi

  if docker volume inspect "$VOLUME_NAME" >/dev/null 2>&1; then
    fail "The PostgreSQL data volume already exists but credentials are missing from $ENV_FILE. Restore the original credentials; do not generate new ones."
  fi

  postgres_db="$DEFAULT_DB"
  postgres_user="$DEFAULT_USER"
  postgres_password="$(openssl rand -hex 32)"
  database_url="postgresql://${postgres_user}:${postgres_password}@postgres:5432/${postgres_db}"

  if ! grep -q '^# PostgreSQL (generated by scripts/deploy-postgres.sh)$' "$ENV_FILE"; then
    printf '\n# PostgreSQL (generated by scripts/deploy-postgres.sh)\n' >> "$ENV_FILE"
  fi
  append_env_value POSTGRES_DB "$postgres_db"
  append_env_value POSTGRES_USER "$postgres_user"
  append_env_value POSTGRES_PASSWORD "$postgres_password"
  append_env_value DATABASE_URL "$database_url"
  echo "==> Appended PostgreSQL credentials and DATABASE_URL to $ENV_FILE"
elif [ -z "$database_url" ]; then
  if [[ ! "$postgres_db" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] ||
     [[ ! "$postgres_user" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] ||
     [[ ! "$postgres_password" =~ ^[A-Za-z0-9._~-]+$ ]]; then
    fail "DATABASE_URL is missing and the existing PostgreSQL credentials require URL encoding. Add a percent-encoded DATABASE_URL to $ENV_FILE."
  fi
  database_url="postgresql://${postgres_user}:${postgres_password}@postgres:5432/${postgres_db}"
  append_env_value DATABASE_URL "$database_url"
  echo "==> Appended DATABASE_URL to $ENV_FILE"
fi

echo "==> Pulling the PostgreSQL image..."
docker compose pull postgres

echo "==> Starting PostgreSQL..."
docker compose up -d postgres

echo "==> Waiting for PostgreSQL readiness..."
ready=false
for _ in {1..60}; do
  if docker compose exec -T postgres pg_isready \
    --username "$postgres_user" \
    --dbname "$postgres_db" >/dev/null 2>&1; then
    ready=true
    break
  fi
  sleep 1
done

if [ "$ready" != true ]; then
  docker compose ps postgres >&2
  docker compose logs --tail 50 postgres >&2
  fail "PostgreSQL did not become ready within 60 seconds."
fi

if ! docker compose exec -T \
  -e PGPASSWORD="$postgres_password" \
  postgres psql \
  --host 127.0.0.1 \
  --username "$postgres_user" \
  --dbname "$postgres_db" \
  --no-psqlrc \
  --tuples-only \
  --command 'SELECT 1;' | grep -q '1'; then
  fail "PostgreSQL is running, but the credentials in $ENV_FILE do not authenticate. Restore the password used to initialize the existing volume."
fi

echo "==> PostgreSQL is healthy and accepts authenticated connections."

echo "==> Building the backend with PostgreSQL support..."
docker compose build backend

echo "==> Applying database migrations..."
docker compose run --rm --no-deps backend npm run db:migrate

echo "==> Recreating the backend with DATABASE_URL..."
docker compose up -d --force-recreate --no-deps backend

echo "==> Waiting for backend and database health..."
backend_ready=false
for _ in {1..60}; do
  health_payload="$(curl --fail --silent http://localhost:3001/healthz 2>/dev/null || true)"
  if printf '%s' "$health_payload" | grep -Eq '"database":\{[^}]*"configured":true[^}]*"connected":true'; then
    backend_ready=true
    break
  fi
  sleep 1
done

if [ "$backend_ready" != true ]; then
  docker compose ps backend postgres >&2
  docker compose logs --tail 50 backend postgres >&2
  fail "The backend did not report a healthy PostgreSQL connection within 60 seconds."
fi

echo "==> Backend health confirms the PostgreSQL connection."
if grep -Eq '^RESEND_API_KEY=.+$' "$ENV_FILE" \
  && grep -Eq '^EMAIL_FROM=.+$' "$ENV_FILE" \
  && grep -Eq '^APP_BASE_URL=.+$' "$ENV_FILE"; then
  echo "==> Starting production health monitor..."
  docker compose up -d --force-recreate --no-deps health-monitor
else
  echo "==> Health alerting disabled until RESEND_API_KEY, EMAIL_FROM, and APP_BASE_URL are configured."
fi
echo "==> Data volume: $VOLUME_NAME"
echo "==> DATABASE_URL is stored in $ENV_FILE (the password was not printed)."
echo "==> PostgreSQL has no public host port; only Compose services can connect."
echo "==> Deployment and migrations complete. Configure an encrypted off-VPS backup before storing production user data."
